name: Send message

on:
  workflow_dispatch:
  push:

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_MESSAGE_THREAD_ID: ${{ secrets.TELEGRAM_MESSAGE_THREAD_ID }}
          NEW_TAG: "20250215"
          TIME: 20250215
        run: |
          MESSAGE="💣 *BOMB DROP* 💣\n*AOSP Kernel*\n*Devices*: POCO X4 GT / Redmi Note 11T Pro (\\+) / K50i (\\xaga)\n*Updated*: $TIME (\\5.10.233)\n\n• Download: [Here](https://github.com/bachnxuan/android_kernel_xiaomi_mt6895/releases/tag/$NEW_TAG)\n\n*Build Config*:\n• Clang 12\n• Thin LTO\n*Feature*:\n• KernelSU-Next & SUSFS 1.5.5\n*Notes*:\n• Only flash with AOSP roms\n• Thanks XagaForce for kernel source\n• AnyKernel3 zips and boot images included\n\nJoin: [bomb kernel chat 💣💣](https://t.me/+jArzTi4u-rhmODU1)\nBy: @reeevrd\n#Kernel #V #AOSP #XAGA"
          
          curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
               -d "chat_id=$TELEGRAM_CHAT_ID" \
               -d "message_thread_id=$TELEGRAM_MESSAGE_THREAD_ID" \
               -d "parse_mode=MarkdownV2" \
               -d "text=${MESSAGE}"
                • Thin LTO
                *Feature*:
                • KernelSU-Next & SUSFS 1.5.5
                *Notes*:  
                • Only flash with AOSP roms
                • Thanks XagaForce for kernel source
                • __AnyKernel3 zips__ and __boot images__ included
                
                Join: [bomb kernel chat 💣💣](https://t.me/+jArzTi4u-rhmODU1)
                By: @reeevrd
                #Kernel #V #AOSP #XAGA"
